# Generated by Django 4.0.4 on 2022-05-01 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationType',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('value', models.IntegerField(null=True)),
                ('startDate', models.DateField(auto_now_add=True, null=True)),
                ('endDate', models.DateField(null=True)),
                ('number_of_employee', models.SmallIntegerField(null=True)),
                ('allocation_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restful_apis.allocationtype')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restful_apis.department')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeInput', models.SmallIntegerField()),
                ('inputDate', models.DateField(auto_now_add=True)),
                ('individualValue', models.SmallIntegerField()),
                ('departmentGoalsId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restful_apis.departmentgoals')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
