# Generated by Django 4.0.4 on 2022-05-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restful_apis', '0005_progress_enddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentgoals',
            name='totalUserContribution',
            field=models.IntegerField(default=0),
        ),
    ]
